#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.luci_app_socat
	set firewall.luci_app_socat=include
	set firewall.luci_app_socat.type=script
	set firewall.luci_app_socat.path=/var/etc/luci-app-socat.include
	set firewall.luci_app_socat.reload=1
	commit firewall
EOF

if [ -x /sbin/fw4 ]; then
	if ! nft -at list chain inet fw4 socat_input >/dev/null 2>&1 ; then
		rm -f /var/etc/socat.include
		# load nftables.d
		fw4 -q reload
	fi
fi
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci-app-socat[-1]
	add ucitrack luci-app-socat
	set ucitrack.@luci-app-socat[-1].init=luci-app-socat
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
