#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci-app-pppoe-relay[-1]
	add ucitrack luci-app-pppoe-relay
	set ucitrack.@luci-app-pppoe-relay[-1].init=luci-app-pppoe-relay
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
