#!/bin/sh

touch /etc/config/luci-app-syncthing

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci-app-syncthing[-1]
	add ucitrack luci-app-syncthing
	set ucitrack.@luci-app-syncthing[-1].exec='/etc/init.d/luci-app-syncthing restart'
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
